#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-tqdm
Version  : 4.63.1
Release  : 117
URL      : https://files.pythonhosted.org/packages/3c/77/e75fb048907ccc065030bf7d9d2d1441247e4e234dbfceb5466207190962/tqdm-4.63.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/3c/77/e75fb048907ccc065030bf7d9d2d1441247e4e234dbfceb5466207190962/tqdm-4.63.1.tar.gz
Summary  : Fast, Extensible Progress Meter
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: pypi-tqdm-bin = %{version}-%{release}
Requires: pypi-tqdm-license = %{version}-%{release}
Requires: pypi-tqdm-python = %{version}-%{release}
Requires: pypi-tqdm-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(colorama)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)

%description
|Logo|
tqdm
====
|Py-Versions| |Versions| |Conda-Forge-Status| |Docker| |Snapcraft|

%package bin
Summary: bin components for the pypi-tqdm package.
Group: Binaries
Requires: pypi-tqdm-license = %{version}-%{release}

%description bin
bin components for the pypi-tqdm package.


%package license
Summary: license components for the pypi-tqdm package.
Group: Default

%description license
license components for the pypi-tqdm package.


%package python
Summary: python components for the pypi-tqdm package.
Group: Default
Requires: pypi-tqdm-python3 = %{version}-%{release}

%description python
python components for the pypi-tqdm package.


%package python3
Summary: python3 components for the pypi-tqdm package.
Group: Default
Requires: python3-core
Provides: pypi(tqdm)
Requires: pypi(colorama)

%description python3
python3 components for the pypi-tqdm package.


%prep
%setup -q -n tqdm-4.63.1
cd %{_builddir}/tqdm-4.63.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648150486
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-tqdm
cp %{_builddir}/tqdm-4.63.1/LICENCE %{buildroot}/usr/share/package-licenses/pypi-tqdm/d710b33bdae7b273ee64376f2e7c722e098079e9
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tqdm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-tqdm/d710b33bdae7b273ee64376f2e7c722e098079e9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
