#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tqdm
Version  : 4.11.1
Release  : 1
URL      : https://pypi.python.org/packages/2e/c8/8085c2adbee07f36274dc46c13193f28c82e56554eb0d6f5be1573a957f3/tqdm-4.11.1.tar.gz
Source0  : https://pypi.python.org/packages/2e/c8/8085c2adbee07f36274dc46c13193f28c82e56554eb0d6f5be1573a957f3/tqdm-4.11.1.tar.gz
Summary  : Fast, Extensible Progress Meter
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: tqdm-bin
Requires: tqdm-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycodestyle
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
|Logo|
tqdm
====
|PyPI-Status| |PyPI-Versions| |Conda-Forge-Status|
|Build-Status| |Coverage-Status| |Branch-Coverage-Status| |Codacy-Grade|

%package bin
Summary: bin components for the tqdm package.
Group: Binaries

%description bin
bin components for the tqdm package.


%package python
Summary: python components for the tqdm package.
Group: Default

%description python
python components for the tqdm package.


%prep
%setup -q -n tqdm-4.11.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485015653
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1485015653
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tqdm

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
